
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA LBRACE LBRACKET NUMBER RBRACE RBRACKET STRINGstart : objectobject : LBRACE RBRACEobject : LBRACE members RBRACEmembers : pairmembers : members COMMA pairpair : STRING COLON valuevalue : STRINGvalue : NUMBERvalue : objectvalue : arrayarray : LBRACKET RBRACKETarray : LBRACKET elements RBRACKETelements : valueelements : elements COMMA value'
    
_lr_action_items = {'LBRACE':([0,10,17,22,],[3,3,3,3,]),'$end':([1,2,4,8,],[0,-1,-2,-3,]),'RBRACE':([3,4,5,6,8,11,12,13,14,15,16,18,21,],[4,-2,8,-4,-3,-5,-7,-6,-8,-9,-10,-11,-12,]),'STRING':([3,9,10,17,22,],[7,7,12,12,12,]),'COMMA':([4,5,6,8,11,12,13,14,15,16,18,19,20,21,23,],[-2,9,-4,-3,-5,-7,-6,-8,-9,-10,-11,22,-13,-12,-14,]),'RBRACKET':([4,8,12,14,15,16,17,18,19,20,21,23,],[-2,-3,-7,-8,-9,-10,18,-11,21,-13,-12,-14,]),'COLON':([7,],[10,]),'NUMBER':([10,17,22,],[14,14,14,]),'LBRACKET':([10,17,22,],[17,17,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'object':([0,10,17,22,],[2,15,15,15,]),'members':([3,],[5,]),'pair':([3,9,],[6,11,]),'value':([10,17,22,],[13,20,23,]),'array':([10,17,22,],[16,16,16,]),'elements':([17,],[19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> object','start',1,'p_start','parser.py',20),
  ('object -> LBRACE RBRACE','object',2,'p_object_empty','parser.py',29),
  ('object -> LBRACE members RBRACE','object',3,'p_object_members','parser.py',38),
  ('members -> pair','members',1,'p_members_single','parser.py',49),
  ('members -> members COMMA pair','members',3,'p_members_multiple','parser.py',54),
  ('pair -> STRING COLON value','pair',3,'p_pair','parser.py',62),
  ('value -> STRING','value',1,'p_value_string','parser.py',72),
  ('value -> NUMBER','value',1,'p_value_number','parser.py',77),
  ('value -> object','value',1,'p_value_object','parser.py',82),
  ('value -> array','value',1,'p_value_array','parser.py',87),
  ('array -> LBRACKET RBRACKET','array',2,'p_array_empty','parser.py',92),
  ('array -> LBRACKET elements RBRACKET','array',3,'p_array_elements','parser.py',96),
  ('elements -> value','elements',1,'p_elements_single','parser.py',100),
  ('elements -> elements COMMA value','elements',3,'p_elements_multiple','parser.py',104),
]
